//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSGalaxy.Common {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMessage() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMSGalaxy.Common.ResMessage", typeof(ResMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}을(를) 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C0001 {
            get {
                return ResourceManager.GetString("C0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}을(를) 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string C0002 {
            get {
                return ResourceManager.GetString("C0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회 조건을 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제할 자료가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 신규 입력상태입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회 할 자료가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0006 {
            get {
                return ResourceManager.GetString("I0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세부자료가 존재하여 삭제할 수 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0007 {
            get {
                return ResourceManager.GetString("I0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 자료가 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0008 {
            get {
                return ResourceManager.GetString("I0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}  삭제 할 수 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0009 {
            get {
                return ResourceManager.GetString("I0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}을(를) 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0011 {
            get {
                return ResourceManager.GetString("I0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출력할 자료가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0012 {
            get {
                return ResourceManager.GetString("I0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}은(는) 입력할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0013 {
            get {
                return ResourceManager.GetString("I0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 할 자료가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0014 {
            get {
                return ResourceManager.GetString("I0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}이(가) 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0020 {
            get {
                return ResourceManager.GetString("I0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일저장용량은 {0} 입니다!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0021 {
            get {
                return ResourceManager.GetString("I0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 권한이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0030 {
            get {
                return ResourceManager.GetString("I0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로 등록할 사진을 선택하여 [저장]하려면, 사진등록을 다시 진행하거나, 아니면 [취소]버튼을 누르세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0031 {
            get {
                return ResourceManager.GetString("I0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 저장이 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0040 {
            get {
                return ResourceManager.GetString("I0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필수 입력에서 누락 항목이 있습니다. 다시 작성하여 주십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I0050 {
            get {
                return ResourceManager.GetString("I0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 올바르지 않습니다. 다시 입력해 주세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I9001 {
            get {
                return ResourceManager.GetString("I9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 로그인 부터 적용됩니다!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string I9101 {
            get {
                return ResourceManager.GetString("I9101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력 또는 변경사항 확인을 무시하고 종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q0000 {
            get {
                return ResourceManager.GetString("Q0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 자료를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q0001 {
            get {
                return ResourceManager.GetString("Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력한 자료를 저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q0002 {
            get {
                return ResourceManager.GetString("Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}을(를) 출력하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q0003 {
            get {
                return ResourceManager.GetString("Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃 하시겠습니까 ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q9910 {
            get {
                return ResourceManager.GetString("Q9910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 을(를) 종료 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q9999 {
            get {
                return ResourceManager.GetString("Q9999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 예외사항 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X0001 {
            get {
                return ResourceManager.GetString("X0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ( {0} ) 에서 정상적이지 않은 결과가 발생했습니다!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X0002 {
            get {
                return ResourceManager.GetString("X0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인터넷에 연결되어있지 않습니다. 네트워크를 확인하세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X9001 {
            get {
                return ResourceManager.GetString("X9001", resourceCulture);
            }
        }
    }
}
